MODEL_NAME = "people-count-random-forest"
MODEL_VERSION = "0.1.0"
FEATURE_SCHEMA_VERSION = "people-count-features-v1"

FEATURE_NAMES = [
    "thermal_available",
    "thermal_frame_count_window",
    "thermal_frame_count_npz",
    "thermal_mean",
    "thermal_std",
    "thermal_min",
    "thermal_max",
    "thermal_p90",
    "thermal_p95",
    "thermal_p99",
    "thermal_hot_threshold",
    "thermal_hot_area_ratio",
    "thermal_hot_region_count",
    "thermal_temporal_std_mean",
    "thermal_frame_diff_mean",
    "thermal_heat_delta_p95_median",
    "radar_available",
    "radar_sample_count",
    "radar_track_count",
    "radar_valid_target_count",
    "radar_target_count_total",
    "radar_mean_speed_cm_s",
    "radar_max_speed_cm_s",
    "sound_available",
    "sound_rms_mean",
    "sound_rms_std",
    "sound_peak",
    "sound_rms_min",
    "sound_rms_max",
    "sound_sample_count",
    "sound_log_rms_mean",
    "sound_peak_to_rms",
    "light_proxy_available",
    "light_normalized_mean",
    "light_normalized_std",
    "light_adc_mean",
    "light_adc_std",
    "light_sample_count",
    "env_temperature_c",
    "env_humidity_pct",
    "env_temp_missing",
    "env_humidity_missing",
    "env_light_lux_missing",
    "quality_completeness",
    "quality_warning_count",
    "sensor_unavailable_count",
    "sensor_degraded_count",
    "window_seconds_actual",
]
